version: '3'

services:
  stakewolle_db:
    container_name: stakewolle_db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  stakewolle_app:
    container_name: stakewolle_app
    build: .
    entrypoint: ["/app/entrypoint-django.sh"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - stakewolle_db




